---
- name: Add Nginx official repository key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
    
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: true
  notify:
    - start nginx