- name: Provision LEMP and related tools
  hosts: server
  remote_user: root
  become: yes
  gather_facts: yes

  roles:
    - update
    - common
    - nginx
    - php
    - mysql
    - initapps
    - restartsvcs