---
- name: MySQL | install mysql packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - mysql-client
    - mysql-common
    - mysql-server


- name: Install python3-pymysql
  apt:
    name: 
      - python3-pymysql
    state: present
  become: yes

- name: MySQL | restart mysql
  service:
    name: mysql
    state: restarted
  become: yes

# - name: MySQL | Set MySQL root password
#   mysql_user:
#     name: root
#     password: ""
#     host_all: yes
#     check_implicit_admin: true
#   become: yes

# - name: MySQL | Delete anonymous MySQL server user
#   mysql_user:
#     name: ""
#     host_all: yes
#     state: absent
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#   become: yes

# - name: MySQL | Secure the MySQL root user for all hosts
#   mysql_user:
#     name: root
#     password: "{{ mysql_root_password }}"
#     host_all: yes
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#   become: yes

# - name: MySQL | Remove the MySQL test database
#   mysql_db:
#     name: test
#     state: absent
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#   become: yes

# - name: MySQL | create application database user
#   mysql_user:
#     name: "{{ mysql_app_user }}"
#     password: "{{ mysql_app_password }}"
#     priv: "*.*:ALL"
#     host: '%'
#     state: present
#     login_user: root
#     login_password: "{{ mysql_root_password }}"
#   become: yes