---
- name: PHP | Install software-properties-common
  ansible.builtin.apt:
    name: software-properties-common
    update_cache: yes

- name: PHP | Install PHP packages
  ansible.builtin.apt:
    name: "php{{ php_version }}-{{ item }}"
    state: present
    update_cache: yes
  loop:
    - fpm
    - cli
    - common
    - curl
    - gd
    - odbc
    - pgsql
    - mbstring
    - mysql
    - xmlrpc
    - opcache
    - intl
    - bz2
    - xml

- name: PHP | Ensure PHP-FPM is started and enabled
  ansible.builtin.service:
    name: "php{{ php_version }}-fpm"
    state: started
    enabled: yes

- name: PHP | Ensure nginx is started and enabled
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes